FROM debian:stable-slim

RUN apt update && apt install -y \
    iputils-ping \
    curl \
    openssh-server \
    openssh-client \
    iproute2 \
    net-tools \
    procps \
    lsof \
    nano \
    vim \
    wget \
    passwd
    
RUN echo "FLAG{player2}" > /root/flag.txt

CMD ["bash"]