FROM debian:stable-slim

RUN apt update && apt install -y \
    iputils-ping \
    curl \
    openssh-server \
    passwd

RUN mkdir -p /var/run/sshd

RUN passwd -d root

RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
RUN echo "PermitEmptyPasswords yes" >> /etc/ssh/sshd_config
RUN echo "UsePAM no" >> /etc/ssh/sshd_config

RUN echo "FLAG{player1}" > /root/flag.txt

CMD service ssh start && /bin/bash