FROM debian:stable-slim

RUN apt update && apt install -y \
    iputils-ping \
    curl \
    openssh-server \
    openssh-client \
    iproute2 \
    net-tools \
    procps \
    lsof \
    nano \
    vim \
    wget \
    passwd

RUN mkdir -p /var/run/sshd

RUN passwd -d root

RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
RUN echo "PermitEmptyPasswords yes" >> /etc/ssh/sshd_config
RUN echo "UsePAM no" >> /etc/ssh/sshd_config

RUN touch /home/user/README.txt
RUN echo "TODO: disable empty password login before production" > /home/user/README.txt

RUN echo "FLAG{player1}" > /root/flag.txt

CMD service ssh start && /bin/bash